[package]
name = "Raptor"
version = "0.1.0"
authors = ["TheAlphaKarp <six.arne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "guessing_game"